#!/usr/bin/env python3
"""
Tempest 4000 (PC) Resolution List Fix - cross-platform patcher
==============================================================

Fixes the launcher of Tempest 4000 (Steam, Llamasoft/Atari, 2018) not listing high
resolutions (1080p / 1440p / 4K ...) on modern GPUs and displays.

Root cause: the launcher walks the DXGI display-mode list but stops after the first
256 *source* entries.  DXGI returns modes sorted ascending by width/height/refresh,
so on a display+GPU that reports more than 256 modes the high-resolution tail is
never examined.  See docs/TECHNICAL.md.

The patch (57 bytes, applied to your own Tempest4000.exe, backup kept):
  A. cap the walk on the number of *accepted* entries instead (the real buffer limit)
  B. skip modes narrower than half the desktop width, so a pathological mode list
     still cannot crowd out the useful resolutions (position-independent code cave)

Usage
-----
  python3 t4k_resfix.py                       # auto-detect Steam install, patch Win10 + Win7-8 exes
  python3 t4k_resfix.py <path\\to\\Tempest4000.exe> [...]
  python3 t4k_resfix.py --check [exe...]      # report state, change nothing
  python3 t4k_resfix.py --restore [exe...]    # put Tempest4000.exe.orig back
  python3 t4k_resfix.py --no-cave ...         # apply only part A (2 bytes)
  python3 t4k_resfix.py --set-mode 3840x2160@60 [prefs.dat]
                                              # pre-select a mode in Tempest4000_UserPrefs.dat
                                              # (optional; you can also just pick it in the launcher)

Requires Python 3.6+ and the 'pefile' package for unknown builds (pip install pefile).
Known Steam builds are patched from an embedded byte table and need no dependencies.
"""
import sys, os, re, struct, hashlib, shutil, glob

__version__ = "1.0.0"
IMAGE_BASE = 0x400000

# ---------------------------------------------------------------------------
# Known builds: sha256 -> (label, patch table).  A table is a list of
# (file_offset, original_bytes_hex, new_bytes_hex).  Generated by --gen-table
# from the signature-based patcher below; embedded so no dependencies are needed.
# ---------------------------------------------------------------------------
KNOWN_BUILDS = {
    # filled in below (see KNOWN_BUILDS_TABLE)
}

# ---------------------------------------------------------------------------
# Signature-based site location (needs pefile). Works on both known Steam builds
# and, in principle, any re-link of the same source.
# ---------------------------------------------------------------------------
def _find_all(hay, pat):
    return [m.start() for m in re.finditer(pat, hay, re.DOTALL)]

def locate_sites(path):
    import pefile
    pe = pefile.PE(path)
    base = pe.OPTIONAL_HEADER.ImageBase
    img = bytes(pe.get_memory_mapped_image())
    text = [s for s in pe.sections if s.Name.startswith(b'.text')][0]
    t0, t1 = text.VirtualAddress, text.VirtualAddress + text.Misc_VirtualSize
    code = img[t0:t1]

    def va2off(va):
        return pe.get_offset_from_rva(va - base)

    R = {'base': base, 'va2off': va2off}
    fmt = "%u x %u @%-d Hz".encode('utf-16-le') + b'\0\0'
    fi = img.find(fmt)
    if fi < 0:
        raise LookupError("listbox format string not found - not a Tempest 4000 launcher build?")
    refs = _find_all(code, re.escape(b'\x68' + struct.pack('<I', base + fi)))
    if len(refs) != 1:
        raise LookupError("expected exactly one reference to the format string, found %d" % len(refs))
    p = refs[0]
    push_fmt = base + t0 + p
    if code[p+5:p+14] != b'\x68\x00\x01\x00\x00\xff\x74\x24\x30' or code[p+14] != 0xe8:
        raise LookupError("unexpected code after 'push fmt'")
    R['push_fmt'] = push_fmt
    R['call_sprintf'] = push_fmt + 14
    R['after_sprintf'] = push_fmt + 19
    m = re.match(rb'\x8b\x15(....)\x83\xc4\x20', code[p+19:p+28], re.DOTALL)
    if not m: raise LookupError("G_OUTARRAY load not found")
    R['g_outarray'] = struct.unpack('<I', m.group(1))[0]
    win = code[p+19:p+19+0x40]
    ms = _find_all(win, rb'\x8b\x3d....\xf2\x0f\x10\x1d')
    if len(ms) != 1: raise LookupError("'mov edi,[G_DESIRED]' not found")
    R['mov_edi_desired'] = push_fmt + 19 + ms[0]
    R['g_desired_disp_va'] = R['mov_edi_desired'] + 2
    R['g_desired'] = struct.unpack('<I', win[ms[0]+2:ms[0]+6])[0]

    lo = p - 0x200; win = code[lo:p]
    ma = _find_all(win, rb'\x81(?:\xfe\x00\x1c|\xf9\x00\x01)\x00\x00\x0f\x8d..\x00\x00')
    if len(ma) != 1: raise LookupError("site A (cmp esi,0x1c00 ; jge) not found")
    R['site_a'] = base + t0 + lo + ma[0]
    R['loop_end'] = R['site_a'] + 12 + struct.unpack('<i', win[ma[0]+8:ma[0]+12])[0]
    ml = _find_all(win[:ma[0]], rb'\xff\x52\x20\x85\xc0\x0f\x88..\x00\x00\x33\xc9')
    if len(ml) != 1: raise LookupError("loop start not found")
    R['call_getdisplaymodelist'] = base + t0 + lo + ml[0]
    R['loop_start'] = R['call_getdisplaymodelist'] + 11
    m = re.match(rb'\x8b\x3d(....)\x8b\x44\x3e\x08', win[ma[0]+12:ma[0]+22], re.DOTALL)
    if not m: raise LookupError("G_MODEARRAY load not found")
    R['g_modearray'] = struct.unpack('<I', m.group(1))[0]
    mb = _find_all(win[ma[0]:], rb'\xf3\x0f\x5e\xc8\x0f\x2f\x0d....(?:\x0f\x82..\x00\x00|\xe9....\x90)')
    if len(mb) != 1: raise LookupError("site B (comiss ; jb) not found")
    b = lo + ma[0] + mb[0] + 4
    R['comiss'] = base + t0 + b
    R['const50_va'] = struct.unpack('<I', code[b+3:b+7])[0]
    R['float50'] = struct.unpack('<f', img[R['const50_va']-base:R['const50_va']-base+4])[0]
    R['jb'] = R['comiss'] + 7
    R['resume'] = R['jb'] + 6
    if code[b+7] == 0xe9:   # already hooked: the cave's first instruction is 'jb skip'
        cave_va = R['jb'] + 5 + struct.unpack('<i', code[b+8:b+12])[0]
        R['skip'] = cave_va + 6 + struct.unpack('<i', img[cave_va-base+2:cave_va-base+6])[0]
    else:
        R['skip'] = R['jb'] + 6 + struct.unpack('<i', code[b+9:b+13])[0]
    mf = _find_all(win[ma[0]:], rb'\xdd\x1c\x24\xe8....\xdd\x5c\x24\x40')
    if len(mf) != 1: raise LookupError("floor call not found")
    R['call_floor'] = base + t0 + lo + ma[0] + mf[0] + 3
    R['after_floor_store'] = R['call_floor'] + 9
    cave = (t1 + 15) & ~15
    R['cave'] = base + cave
    R['cave_limit'] = base + t0 + text.SizeOfRawData
    R['cave_empty'] = all(x == 0 for x in img[cave:t0 + text.SizeOfRawData])
    if R['cave_limit'] - R['cave'] < 64:
        raise LookupError("not enough .text padding for the code cave")
    if abs(R['float50'] - 50.0) > 1e-6:
        raise LookupError("unexpected refresh threshold constant %r" % R['float50'])
    return R

# ---------------------------------------------------------------------------
# Patch construction
# ---------------------------------------------------------------------------
def _rel32(src_end, dst):
    return struct.pack('<i', dst - src_end)

def build_patch_table(R, cave=True):
    """Return [(file_offset, old_bytes, new_bytes)] for the given site map."""
    va2off = R['va2off']
    table = []
    # A: cmp esi,0x1c00 -> cmp ecx,0x100
    table.append((va2off(R['site_a']), bytes.fromhex('81fe001c0000'), bytes.fromhex('81f900010000')))
    if cave:
        # hook: replace 'jb skip' (6 bytes) with 'jmp cave ; nop'.  The comiss before it stays,
        # and its flags are still valid when the cave's first instruction runs.
        jb_old = b'\x0f\x82' + _rel32(R['jb'] + 6, R['skip'])
        hook = b'\xe9' + _rel32(R['jb'] + 5, R['cave']) + b'\x90'
        table.append((va2off(R['jb']), jb_old, hook))
        # cave (position independent: reads the loader-relocated &G_DESIRED out of the
        # original 'mov edi,[G_DESIRED]' instruction instead of embedding an address)
        c = b''; a = R['cave']
        ins = b'\x0f\x82' + _rel32(a + 6, R['skip']); c += ins; a += len(ins)   # jb skip
        ins = b'\xe8\x00\x00\x00\x00';                 c += ins; a += len(ins)   # call $+5
        pop_va = a
        ins = b'\x58';                                 c += ins; a += len(ins)   # pop eax  (eax = pop_va)
        delta = R['g_desired_disp_va'] - pop_va
        ins = b'\x8b\x80' + struct.pack('<i', delta);  c += ins; a += len(ins)   # mov eax,[eax+delta]
        ins = b'\x8b\x00';                             c += ins; a += len(ins)   # mov eax,[eax]
        ins = b'\x8b\x40\x1c';                         c += ins; a += len(ins)   # mov eax,[eax+0x1c] desktop width
        ins = b'\xd1\xe8';                             c += ins; a += len(ins)   # shr eax,1
        ins = b'\x39\x04\x3e';                         c += ins; a += len(ins)   # cmp [esi+edi],eax
        ins = b'\x0f\x82' + _rel32(a + 6, R['skip']); c += ins; a += len(ins)   # jb skip
        ins = b'\xe9' + _rel32(a + 5, R['resume']);   c += ins; a += len(ins)   # jmp resume
        assert a <= R['cave_limit']
        table.append((va2off(R['cave']), b'\0' * len(c), c))
    return table

# ---------------------------------------------------------------------------
# Applying / checking tables
# ---------------------------------------------------------------------------
def row_state(data, row):
    off, old, new = row
    cur = bytes(data[off:off+len(old)])
    return 'orig' if cur == old else 'patched' if cur == new else 'unknown'

def table_state(data, table):
    """Human-readable state: part A is row 0, part B is rows 1.. (hook + cave)."""
    a = row_state(data, table[0])
    b = {row_state(data, r) for r in table[1:]}
    if len(table) == 1:
        return a
    if b == {'orig'}: bs = 'orig'
    elif b == {'patched'}: bs = 'patched'
    else: bs = 'unknown'
    return "A: %s, B: %s" % (a, bs)

def apply_table(data, table):
    """Apply rows that are still original; skip rows already patched. Returns bytes changed."""
    n = 0
    for row in table:
        st = row_state(data, row)
        if st == 'unknown':
            raise LookupError("unexpected bytes at file offset %#x - refusing to touch this file" % row[0])
        if st == 'orig':
            data[row[0]:row[0]+len(row[2])] = row[2]; n += len(row[2])
    return n

def sha256(data):
    return hashlib.sha256(data).hexdigest()

def table_for_file(path, data, want_cave, force):
    """Pick the embedded table for a known build, else locate by signature."""
    h = sha256(data)
    if h in KNOWN_BUILDS:
        label, full = KNOWN_BUILDS[h]
        return label, full if want_cave else full[:1]
    # maybe already patched: compare against patched hashes
    for oh, (label, full) in KNOWN_BUILDS.items():
        for tbl in (full, full[:1]):
            probe = bytearray(data)
            if table_state(probe, tbl) == 'patched':
                return label, full if want_cave else full[:1]
    if not force:
        raise LookupError("unknown build (sha256 %s). Use --force to try signature-based patching." % h)
    R = locate_sites(path)
    if want_cave and not R['cave_empty'] and row_state(data, build_patch_table(R, cave=True)[2]) != 'patched':
        raise LookupError(".text padding is not empty - cannot place code cave (try --no-cave)")
    return "unknown build (signature-located)", build_patch_table(R, cave=want_cave)

# ---------------------------------------------------------------------------
# Prefs file: pre-select a mode (CRC-16/XMODEM over the first 0x894 bytes at 0x894)
# ---------------------------------------------------------------------------
PREFS_SIZE, PREFS_MODE_OFF, PREFS_CRC_OFF = 0x898, 0x818, 0x894
PREFS_MAGIC = b'LE MAN SUL CUL!'

def crc16_xmodem(buf):
    crc = 0
    for b in buf:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xffff if crc & 0x8000 else (crc << 1) & 0xffff
    return crc

def set_mode(prefs_path, spec):
    m = re.fullmatch(r'\s*(\d+)\s*[xX]\s*(\d+)\s*@\s*(\d+(?:\.\d+)?)\s*(?:[Hh][Zz])?\s*', spec)
    if not m:
        raise ValueError("mode must look like 3840x2160@60 (fractional refresh like 59.94 is fine)")
    w, h, hz = int(m.group(1)), int(m.group(2)), m.group(3)
    if '.' in hz:
        den = 10 ** len(hz.split('.')[1]); num = int(round(float(hz) * den))
    else:
        num, den = int(hz), 1
    d = bytearray(open(prefs_path, 'rb').read())
    if len(d) != PREFS_SIZE or not d.startswith(PREFS_MAGIC):
        raise ValueError("not a Tempest4000_UserPrefs.dat (size %d)" % len(d))
    if crc16_xmodem(d[:PREFS_CRC_OFF]) != struct.unpack_from('<I', d, PREFS_CRC_OFF)[0]:
        print("warning: existing prefs checksum did not verify (file will be rewritten anyway)")
    old = struct.unpack_from('<IIII', d, PREFS_MODE_OFF)
    struct.pack_into('<IIII', d, PREFS_MODE_OFF, w, h, num, den)
    struct.pack_into('<I', d, PREFS_CRC_OFF, crc16_xmodem(d[:PREFS_CRC_OFF]))
    bak = prefs_path + '.orig'
    if not os.path.exists(bak):
        shutil.copy2(prefs_path, bak)
    open(prefs_path, 'wb').write(d)
    print("prefs: %dx%d @ %s Hz -> %dx%d @ %s Hz   (%s, backup %s)" % (
        old[0], old[1], "%g" % (old[2] / old[3] if old[3] else 0), w, h, hz, prefs_path, bak))

def default_prefs_path():
    home = os.environ.get('USERPROFILE') or os.path.expanduser('~')
    cands = [os.path.join(home, 'Documents', 'Tempest4000_Savedata', 'Tempest4000_UserPrefs.dat')]
    # Proton prefix (Linux / Steam Deck)
    for lib in steam_libraries():
        cands += glob.glob(os.path.join(lib, 'steamapps', 'compatdata', '688140', 'pfx', 'drive_c',
                                        'users', '*', 'Documents', 'Tempest4000_Savedata', 'Tempest4000_UserPrefs.dat'))
    for c in cands:
        if os.path.exists(c):
            return c
    return None

# ---------------------------------------------------------------------------
# Locating the game
# ---------------------------------------------------------------------------
def steam_libraries():
    roots = []
    if sys.platform == 'win32':
        try:
            import winreg
            for hive, key in ((winreg.HKEY_CURRENT_USER, r'Software\Valve\Steam'),
                              (winreg.HKEY_LOCAL_MACHINE, r'SOFTWARE\WOW6432Node\Valve\Steam')):
                try:
                    with winreg.OpenKey(hive, key) as k:
                        v = winreg.QueryValueEx(k, 'SteamPath' if hive == winreg.HKEY_CURRENT_USER else 'InstallPath')[0]
                        roots.append(v.replace('/', '\\'))
                except OSError:
                    pass
        except ImportError:
            pass
        roots += [r'C:\Program Files (x86)\Steam', r'C:\Program Files\Steam']
    else:
        home = os.path.expanduser('~')
        roots += [os.path.join(home, '.steam', 'steam'), os.path.join(home, '.local', 'share', 'Steam'),
                  os.path.join(home, '.var', 'app', 'com.valvesoftware.Steam', '.local', 'share', 'Steam')]
    libs = []
    for r in roots:
        if not os.path.isdir(r):
            continue
        libs.append(r)
        vdf = os.path.join(r, 'steamapps', 'libraryfolders.vdf')
        if os.path.exists(vdf):
            for m in re.finditer(r'"path"\s+"([^"]+)"', open(vdf, encoding='utf-8', errors='replace').read()):
                libs.append(m.group(1).replace('\\\\', '\\'))
    seen, out = set(), []
    for l in libs:
        n = os.path.normcase(os.path.normpath(l))
        if n not in seen and os.path.isdir(l):
            seen.add(n); out.append(l)
    return out

def find_game_exes():
    found = []
    for lib in steam_libraries():
        for sub in ('Win10', 'Win7-8'):
            p = os.path.join(lib, 'steamapps', 'common', 'Tempest 4000', sub, 'Tempest4000.exe')
            if os.path.exists(p):
                found.append(p)
    return found

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main(argv):
    flags = {a for a in argv if a.startswith('--')}
    args = [a for a in argv if not a.startswith('--')]
    if '--help' in flags or '-h' in argv:
        print(__doc__); return 0
    if '--version' in flags:
        print(__version__); return 0

    if '--set-mode' in flags:
        i = argv.index('--set-mode')
        spec = argv[i+1] if i + 1 < len(argv) else ''
        rest = [a for a in args if a != spec]
        p = rest[0] if rest else default_prefs_path()
        if not p:
            print("prefs file not found - launch the game once first, or pass its path"); return 1
        set_mode(p, spec); return 0

    if '--gen-table' in flags:
        for path in args:
            data = open(path, 'rb').read()
            R = locate_sites(path)
            tbl = build_patch_table(R, cave=True)
            print("    %r: (%r, [" % (sha256(data), os.path.basename(path)))
            for off, old, new in tbl:
                print("        (0x%x, %r, %r)," % (off, old.hex(), new.hex()))
            print("    ]),")
        return 0

    exes = args or find_game_exes()
    if not exes:
        print("Tempest4000.exe not found. Pass its path, e.g.\n"
              '  "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Tempest 4000\\Win10\\Tempest4000.exe"')
        return 1
    rc = 0
    for path in exes:
        print("== %s" % path)
        try:
            if '--restore' in flags:
                bak = path + '.orig'
                if not os.path.exists(bak):
                    print("   no backup found (%s). Use Steam > Verify integrity of game files." % bak); rc = 1; continue
                shutil.copy2(bak, path); print("   restored from", bak); continue
            data = bytearray(open(path, 'rb').read())
            label, table = table_for_file(path, data, want_cave='--no-cave' not in flags, force='--force' in flags)
            state = table_state(data, table)
            print("   build: %s   state: %s" % (label, state))
            if '--check' in flags:
                continue
            if all(row_state(data, r) == 'patched' for r in table):
                print("   already patched - nothing to do"); continue
            bak = path + '.orig'
            if not os.path.exists(bak):
                shutil.copy2(path, bak); print("   backup:", bak)
            n = apply_table(data, table)
            open(path, 'wb').write(data)
            print("   patched (%d bytes changed). sha256: %s" % (n, sha256(data)))
        except PermissionError:
            print("   permission denied - run from an elevated prompt or check the folder is writable"); rc = 1
        except LookupError as e:
            print("   %s" % e); rc = 1
    return rc

# ---------------------------------------------------------------------------
# Embedded tables for the known Steam builds (regenerate with: --gen-table <exe>)
# ---------------------------------------------------------------------------
KNOWN_BUILDS_TABLE = {
    # Steam depot, Win10\Tempest4000.exe  (link date 2018-10-09, D3DCOMPILER_47 / XINPUT1_4)
    '591fa01282c4a62eaed8583dac845c369d9330e7e5052e95856b80c8eba2fb1a': ('Steam Win10 build (2018-10-09)', [
        (0x8e690, '81fe001c0000', '81f900010000'),
        (0x8e6e5, '0f82f7010000', 'e97601020090'),
        (0xae860, '000000000000000000000000000000000000000000000000000000000000000000000000000000', '0f827c00feffe800000000588b8031fffdff8b008b401cd1e839043e0f826000feffe964fefdff'),
    ]),
    # Steam depot, Win7-8\Tempest4000.exe  (link date 2018-10-12, D3DCOMPILER_43 / XINPUT1_3)
    '411aa66ab702b21c4e0949e4049b486aeb88325786c3f6d14a853888058a9b9b': ('Steam Win7-8 build (2018-10-12)', [
        (0x8e720, '81fe001c0000', '81f900010000'),
        (0x8e775, '0f82f7010000', 'e97601020090'),
        (0xae8f0, '000000000000000000000000000000000000000000000000000000000000000000000000000000', '0f827c00feffe800000000588b8031fffdff8b008b401cd1e839043e0f826000feffe964fefdff'),
    ]),
}
for _h, (_label, _rows) in KNOWN_BUILDS_TABLE.items():
    KNOWN_BUILDS[_h] = (_label, [(o, bytes.fromhex(a), bytes.fromhex(b)) for o, a, b in _rows])

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
